- name: Update status file - 22f2001290@ds.study.iitm.ac.in
  run: |
    echo "Updated on $(date)" >> daily_log.txt
    git config --global user.name "github-actions[bot]"
    git config --global user.email "22f2001290@ds.study.iitm.ac.in"
    git add daily_log.txt
    git commit -m "Daily update: $(date)" || echo "No changes to commit"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
